### ISSUE TITLE
User's privacy

### ISSUE THREAD

**Issue by asegursa** [wheelybird/openvpn-server-ldap-otp#27]
Hi. This is not an issue, it's a question.

I have a running and working VPN using this project and I have some doubts regarding the privacy of the communications between users using the same VPN. In my environment I have LDAP authentication so, in order to establish a connection, each user has to provide its credentials (TLS is activated through all the authentication process). Let's say I have, at the same moment, 10 users using the VPN. Will they be able to MITM attack communications of the other users? As I don't know if this container uses the same key for each user I can't be sure if they are able to spy each other.

Thanks!

**Comment by wheelybird** [comment]
Hi.  This depends on how you set up the VPN tunnels and is more of a question to ask the OpenVPN community.   There's an OpenVPN option (client-to-client) that allows clients to communicate "directly" (i.e. the OpenVPN daemon handles the routing rather than the underlying host).  This isn't enabled by default and this container doesn't offer enabling it as an option.  Without this enabled clients might still be able to connect to each other via the host if network forwarding is enabled and the appropriate routes are set up.  This StackExchange page explains this more fully:  https://serverfault.com/questions/736274/openvpn-client-to-client
With regards to MITM attacks, that's an unlikely scenario as you'd need to somehow route to the intended destination _via_ one of the other clients, which means that whoever intends to create the MITM attack would need to somehow force another client to route via their PC (i.e. change the DNS lookups).  So, as always, it's up to you or the users to ensure that their OS is as secure as it can be.
