### ISSUE TITLE
Enable to acces to other docker on  the host

### ISSUE THREAD

**Issue by atila01380** [wheelybird/openvpn-server-ldap-otp#33]
Hi,

I have an host with containers. 

- portainer
- nginx 
- openvpn-server-ldap-otp

When i was connect from  outside with OpenVPN i  can't access to  the other docker like portainer or nginx on my host. But i  can acces to  other server on my  LAN.

Do you  have an  idea ?

Does openvpn-server-ldap-otp need specific docker network ?
Does openvpn-server-ldap-otp need specific route ?

Thanks for all.

Bertrand

**Comment by wheelybird** [comment]
Hi.  It's hard to say what your issue is as I don't know how you've set up those services.
If you've set up OpenVPN in NAT mode (the default) and the other containers have had their ports exposed on the host then you ought to be able to connect to them (you said you can access the other servers on the LAN, so that suggests you've got that routing set up for the subnet the host's on correctly).
You could try adding "172.17.0.1 255.255.255.255" as a route - that's the default docker interface (double-check it's the same on your host) and connecting to the appropriate ports on that IP.
